name: Deploy

on:
    push:
        branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Deploy to Render
          env:
            RENDER_WEBHOOK_URL: ${{ secrets.RENDER_WEBHOOKURL }}
          run: |
            curl -X GET \ $RENDER_WEBHOOK_URL